services:
  - type: web
    name: bbadoc
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python testup.py --web
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: UPSTAGE_API_KEY
        fromGroup: bbadoc-secrets
      - key: KAKAO_CLIENT_ID
        fromGroup: bbadoc-secrets
      - key: KAKAO_REDIRECT_URI
        fromGroup: bbadoc-secrets